# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clementi Mattia - Web Developer
email: ilcleme@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sono Mattia, laureato in Tecnologie Web, lavoro come Web Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mattiaclementi.it" # the base hostname & protocol for your site
twitter_username: MattiaClementi
github_username:  ilCleme
linkedin_username: mattia-clementi

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
